server:
  port : 8082
spring:
  profiles:
    active: local
  application:
    name: "spring-boot-jpa-example"
  datasource:
    url: "jdbc:mysql://localhost:3306/spring-boot-jpa-example"
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true